# version: '3.8'

services:
  go-backend:
    build:
      context: .
    ports:
      # - "127.0.0.1:8080:8080"
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    networks:
      - static_net

networks:
  static_net:    
    external: true
