// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login-guru": {
            "post": {
                "description": "Log In",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "Create user request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/login.AuthGuruRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/login.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login-ketua-kelas": {
            "post": {
                "description": "Log In",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "Create user request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/login.AuthKetuaKelasRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/login.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/guru": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all guru",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "guru"
                ],
                "summary": "Get all guru",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/getall.GetAllGuruResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/guru/register": {
            "post": {
                "description": "Create Guru request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "guru"
                ],
                "summary": "Mendaftarkan guru baru",
                "parameters": [
                    {
                        "description": "Create guru request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create.CreateGuruRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/create.CreateGuruResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/guru/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a guru by ID, only fields provided will be updated",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "guru"
                ],
                "summary": "Update guru data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guru ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Guru update data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/update.UpdateGuruRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/update.UpdateGuruResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a guru by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "guru"
                ],
                "summary": "Delete a guru",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Guru ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/jurusan": {
            "get": {
                "description": "Get list of all jurusan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jurusan"
                ],
                "summary": "Get all jurusan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/getall.GetAllJurusanResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new jurusan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jurusan"
                ],
                "summary": "Create jurusan",
                "parameters": [
                    {
                        "description": "Jurusan body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create.CreateJurusanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/create.CreateJurusanResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/jurusan/{id}": {
            "get": {
                "description": "Get jurusan details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jurusan"
                ],
                "summary": "Get jurusan by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jurusan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/getbyid.GetJurusanResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update jurusan data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jurusan"
                ],
                "summary": "Update jurusan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jurusan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Jurusan data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/update.UpdateJurusanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/update.UpdateJurusanResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete jurusan by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jurusan"
                ],
                "summary": "Delete jurusan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jurusan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ketua-kelas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all ketua kelas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ketua kelas"
                ],
                "summary": "Get all ketua kelas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/getall.GetAllKetuaKelasResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ketua-kelas/register": {
            "post": {
                "description": "Create Ketua Kelas baru request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ketua kelas"
                ],
                "summary": "Create Ketua Kelas request body",
                "parameters": [
                    {
                        "description": "Create ketua request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create.CreateKetuaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/create.CreateKetuaResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ketua-kelas/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete Ketua Kelas by ID",
                "tags": [
                    "ketua kelas"
                ],
                "summary": "Delete Ketua Kelas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ketua Kelas ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/mapel": {
            "get": {
                "description": "Get all mata pelajaran",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapel"
                ],
                "summary": "Get all mapel",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/getall.GetAllMapelResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new mata pelajaran",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapel"
                ],
                "summary": "Create mapel",
                "parameters": [
                    {
                        "description": "Mapel body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create.CreateMapelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/create.CreateMapelResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/mapel/{id}": {
            "get": {
                "description": "Get a mata pelajaran by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapel"
                ],
                "summary": "Get mapel by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mapel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/getbyid.GetMapelByIDResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update a mata pelajaran by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapel"
                ],
                "summary": "Update mapel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mapel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Mapel body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/update.UpdateMapelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/update.UpdateMapelResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a mapel by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapel"
                ],
                "summary": "Delete mapel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mapel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ruangan": {
            "get": {
                "description": "Get all ruangan records",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ruangan"
                ],
                "summary": "Get all ruangan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/getall.GetAllRuanganResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new ruangan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ruangan"
                ],
                "summary": "Create ruangan",
                "parameters": [
                    {
                        "description": "Ruangan body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create.CreateRuanganRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/create.CreateRuanganResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ruangan/{id}": {
            "get": {
                "description": "Get a ruangan by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ruangan"
                ],
                "summary": "Get ruangan by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ruangan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/getbyid.GetRuanganByIDResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update a ruangan by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ruangan"
                ],
                "summary": "Update ruangan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ruangan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Ruangan body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/update.UpdateRuanganRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/update.UpdateRuanganResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a ruangan by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ruangan"
                ],
                "summary": "Delete ruangan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ruangan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Logged user profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/getprofile.GetUserResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "Create user request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/create.CreateUserResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "create.CreateGuruRequest": {
            "description": "Create guru request body",
            "type": "object",
            "properties": {
                "jabatan": {
                    "description": "@Description Jabatan of the guru\n@Required true\n@Enum \"guru\" \"kepala_sekolah\"\n@Example \"guru\"",
                    "type": "string"
                },
                "nama": {
                    "description": "@Description Name of the guru\n@Required true\n@Example \"John Doe\"",
                    "type": "string"
                },
                "nip": {
                    "description": "@Description NIP of the guru\n@Required true\n@Example \"123456789\"",
                    "type": "string"
                },
                "password": {
                    "description": "@Description Password of the guru\n@Required true\n@Example \"password123\"\n@MinLength 6",
                    "type": "string"
                }
            }
        },
        "create.CreateGuruResponse": {
            "type": "object",
            "properties": {
                "jabatan": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                }
            }
        },
        "create.CreateGuruResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/create.CreateGuruResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "create.CreateJurusanRequest": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "create.CreateJurusanResponse": {
            "type": "object",
            "properties": {
                "jurusan_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "create.CreateJurusanResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/create.CreateJurusanResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "create.CreateKetuaRequest": {
            "description": "Create ketua request body NISN of the ketua",
            "type": "object",
            "properties": {
                "nama": {
                    "description": "@Description Name of the ketua\n@Required true\n@Example \"John Doe\"",
                    "type": "string"
                },
                "nisn": {
                    "description": "@Description NISN of the ketua\n@Required true\n@Example \"123456789\"",
                    "type": "string"
                },
                "password": {
                    "description": "@Description Password of the ketua\n@Required true\n@Example \"password123\"\n@MinLength 6",
                    "type": "string"
                }
            }
        },
        "create.CreateKetuaResponse": {
            "type": "object",
            "properties": {
                "nama": {
                    "type": "string"
                },
                "nisn": {
                    "type": "string"
                }
            }
        },
        "create.CreateKetuaResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/create.CreateKetuaResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "create.CreateMapelRequest": {
            "type": "object",
            "required": [
                "jurusan_id",
                "nama"
            ],
            "properties": {
                "jurusan_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "create.CreateMapelResponse": {
            "type": "object",
            "properties": {
                "jurusan_id": {
                    "type": "string"
                },
                "mapel_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "create.CreateMapelResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/create.CreateMapelResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "create.CreateRuanganRequest": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "create.CreateRuanganResponse": {
            "type": "object",
            "properties": {
                "nama": {
                    "type": "string"
                },
                "ruangan_id": {
                    "type": "string"
                }
            }
        },
        "create.CreateRuanganResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/create.CreateRuanganResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "create.CreateUserRequest": {
            "description": "Create user request body",
            "type": "object",
            "properties": {
                "email": {
                    "description": "Your Email",
                    "type": "string"
                },
                "name": {
                    "description": "Your Name",
                    "type": "string"
                },
                "password": {
                    "description": "Your Password",
                    "type": "string"
                }
            }
        },
        "create.CreateUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "create.CreateUserResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/create.CreateUserResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "getall.GetAllGuruResponse": {
            "description": "Get all guru response",
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID of the guru\n@example 1",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the guru\n@example John Doe",
                    "type": "string"
                },
                "nip": {
                    "description": "NIP of the guru\n@example 1234567890",
                    "type": "string"
                }
            }
        },
        "getall.GetAllJurusanResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/getall.JurusanResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "getall.GetAllKetuaKelasResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "@Description ID of the ketua\n@Required true\n@Example \"123e4567-e89b-12d3-a456-426614174000\"",
                    "type": "string"
                },
                "nama": {
                    "description": "@Description Name of the ketua\n@Required true\n@Example \"John Doe\"",
                    "type": "string"
                },
                "nisn": {
                    "description": "@Description NISN of the ketua\n@Required true\n@Example \"123456789\"",
                    "type": "string"
                }
            }
        },
        "getall.GetAllMapelResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/getall.MapelResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "getall.GetAllRuanganResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/getall.RuanganResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "getall.JurusanResponse": {
            "type": "object",
            "properties": {
                "jurusan_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "getall.MapelResponse": {
            "type": "object",
            "properties": {
                "jurusan_id": {
                    "type": "string"
                },
                "mapel_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "getall.RuanganResponse": {
            "type": "object",
            "properties": {
                "nama": {
                    "type": "string"
                },
                "ruangan_id": {
                    "type": "string"
                }
            }
        },
        "getbyid.GetJurusanResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/getbyid.JurusanResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "getbyid.GetMapelByIDResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/getbyid.MapelResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "getbyid.GetRuanganByIDResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/getbyid.RuanganResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "getbyid.JurusanResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "jurusan_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "getbyid.MapelResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "jurusan_id": {
                    "type": "string"
                },
                "mapel_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "getbyid.RuanganResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "ruangan_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "getprofile.GetUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "login.AuthGuruRequest": {
            "type": "object",
            "properties": {
                "nip": {
                    "description": "Your NIP",
                    "type": "string"
                },
                "password": {
                    "description": "Your Password",
                    "type": "string"
                }
            }
        },
        "login.AuthKetuaKelasRequest": {
            "description": "Login ketua kelas request body",
            "type": "object",
            "properties": {
                "nisn": {
                    "description": "Your NISN",
                    "type": "string"
                },
                "password": {
                    "description": "Your Password",
                    "type": "string"
                }
            }
        },
        "login.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "update.UpdateGuruRequest": {
            "type": "object",
            "properties": {
                "jabatan": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "update.UpdateGuruResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jabatan": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "update.UpdateJurusanRequest": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "update.UpdateJurusanResponse": {
            "type": "object",
            "properties": {
                "jurusan_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "update.UpdateJurusanResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/update.UpdateJurusanResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "update.UpdateMapelRequest": {
            "type": "object",
            "required": [
                "jurusan_id",
                "nama"
            ],
            "properties": {
                "jurusan_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "update.UpdateMapelResponse": {
            "type": "object",
            "properties": {
                "jurusan_id": {
                    "type": "string"
                },
                "mapel_id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "update.UpdateMapelResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/update.UpdateMapelResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "update.UpdateRuanganRequest": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "update.UpdateRuanganResponse": {
            "type": "object",
            "properties": {
                "nama": {
                    "type": "string"
                },
                "ruangan_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "update.UpdateRuanganResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/update.UpdateRuanganResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Monitoring Guru",
	Description:      "endpoints for monitoring guru XD",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
